services:
  mysql:
    image: mysql:9.2.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=chirper-user
      - MYSQL_PASSWORD=chirper-password
      - MYSQL_DATABASE=chirper-database